### ISSUE TITLE
Install OGGM failed in winodws10, Anaconda (python 3.6). Does anyone meet the same issues?

### ISSUE THREAD

**Issue by liyaojun** [OGGM/oggm#589] opened 2018-11-05 07:50 UTC
I have been installing OGGM in win10, Anaconda(python 3.6) but always failed. I have installed all needed packages manually following #588, and created oggm environment. but I failed to install OGGM by conda install or pip install. However,  I cloned the git repository successfully and also can run setup.py develop for oggm, showed  installed oggm successfully. But failed to run pytest . .
Besides, I can import oggm in commd prompt works but can't in spyder (my favorite editor). Moreover, even import oggm successfully in cmd, i still can't import any modules from oggm.
 I have install oggm successfully which also means I have installed all packages successfully.
![1](https://user-images.githubusercontent.com/19677300/47984196-cbd10680-e110-11e8-85cb-f23589792a48.png)
Failed to install oggm by conda
![2](https://user-images.githubusercontent.com/19677300/47984272-1a7ea080-e111-11e8-968e-7ecb0f36db7e.png)
Failed to pass the pytest .
![3](https://user-images.githubusercontent.com/19677300/47984327-413cd700-e111-11e8-96d8-32344ebfde9f.png)
Successfully import in cmd but failed import any modules from oggm
![4](https://user-images.githubusercontent.com/19677300/47984543-e22b9200-e111-11e8-8e43-7756d46b9640.png)
Failed imprt oggm in spyder
![5](https://user-images.githubusercontent.com/19677300/47984740-7e559900-e112-11e8-9689-28426fa69026.png)

**Comment by TimoRoth** [comment] 2018-11-05 09:31
I'm sadly not sure how to correctly setup Spyder. But from the looks of it, it's using the wrong python interpreter. It has to use the one conda installed in your OGGM environment. The path it points to is in the "my_root" environment instead of the oggm_env.
Same for when you can import oggm, but not oggm.utils. Are you in the right environment there? The one where you ran pip install for oggm in?

**Comment by MatCast** [comment] 2018-11-05 10:44
In Spyder in order to use a different environment from the default one you have to go to:
Tools->Preferences->Python Interpreter: Choose "Use the following Python interpreter" and choose the path to the python installation of the oggm environment. Usually this is in the anaconda3 folder: path/to/anaconda3/envs/oggm_env/bin/python3.6.
![spyder_preferences](https://user-images.githubusercontent.com/32680270/47993580-1aba7400-e0f0-11e8-943a-88aabda24826.png)

After this you need to restart the kernel of the ipython console. You should now be able to import oggm if it is correctly installed.

**Comment by liyaojun** [comment] 2018-11-05 11:58
> I'm sadly not sure how to correctly setup Spyder. But from the looks of it, it's using the wrong python interpreter. It has to use the one conda installed in your OGGM environment. The path it points to is in the "my_root" environment instead of the oggm_env.
> Same for when you can import oggm, but not oggm.utils. Are you in the right environment there? The one where you ran pip install for oggm in?
I attached all the screen shots in my installation in order. Hope this will help find the problem. Besides, I installed the OGGM in anaconda root.
![1](https://user-images.githubusercontent.com/19677300/47996842-e026fa80-e134-11e8-9379-0b0721f02ad1.png)
![2](https://user-images.githubusercontent.com/19677300/47996856-e917cc00-e134-11e8-8c90-befeee6f9060.png)
![3](https://user-images.githubusercontent.com/19677300/47996857-e917cc00-e134-11e8-82f3-b75a065945be.png)
![4](https://user-images.githubusercontent.com/19677300/47996858-e9b06280-e134-11e8-8f30-bb34968a7014.png)
![5](https://user-images.githubusercontent.com/19677300/47996859-e9b06280-e134-11e8-81a0-2df3b8efca81.png)
![6](https://user-images.githubusercontent.com/19677300/47996861-ea48f900-e134-11e8-8e29-e0ad2abda386.png)
![7](https://user-images.githubusercontent.com/19677300/47996862-ea48f900-e134-11e8-87e8-a4f447c44e06.png)
![8](https://user-images.githubusercontent.com/19677300/47996864-eae18f80-e134-11e8-8e6b-8738c17075eb.png)
![9](https://user-images.githubusercontent.com/19677300/47996865-eae18f80-e134-11e8-8602-176045f7d4e1.png)

**Comment by liyaojun** [comment] 2018-11-05 12:00
> In Spyder in order to use a different environment from the default one you have to go to:
> Tools->Preferences->Python Interpreter: Choose "Use the following Python interpreter" and choose the path to the python installation of the oggm environment. Usually this is in the anaconda3 folder: path/to/anaconda3/envs/oggm_env/bin/python3.6.
> ![spyder_preferences](https://user-images.githubusercontent.com/32680270/47993580-1aba7400-e0f0-11e8-943a-88aabda24826.png)
> 
> After this you need to restart the kernel of the ipython console. You should now be ab

**Comment by liyaojun** [comment] 2018-11-05 12:02
> In Spyder in order to use a different environment from the default one you have to go to:
> Tools->Preferences->Python Interpreter: Choose "Use the following Python interpreter" and choose the path to the python installation of the oggm environment. Usually this is in the anaconda3 folder: path/to/anaconda3/envs/oggm_env/bin/python3.6.
> ![spyder_preferences](https://user-images.githubusercontent.com/32680270/47993580-1aba7400-e0f0-11e8-943a-88aabda24826.png)
> 
> After this you need to restart the kernel of the ipython console. You should now be able to import oggm if it is correctly installed.

After the environment changed, could all packages I have installed except oggm be imported in Spyder?

**Comment by liyaojun** [comment] 2018-11-05 12:05
> I'm sadly not sure how to correctly setup Spyder. But from the looks of it, it's using the wrong python interpreter. It has to use the one conda installed in your OGGM environment. The path it points to is in the "my_root" environment instead of the oggm_env.
> Same for when you can import oggm, but not oggm.utils. Are you in the right environment there? The one where you ran pip install for oggm in?

After the pytest, it showed " oggm.utils: Downloading https://github.com/OGGM/oggm-sample-data/archive/657ecfd463fbd5e43c5d138085a484947a464649.zip to C:\Users\ThinkPad\OGGM\download_cache\github.com/OGGM/oggm-sample-data/archive/657ecfd463fbd5e43c5d138085a484947a464649.zip..."

In my first installation, it has showed downloading sample data. But after 4 or 5 hours, it still running and without any progress. So I shut down the root and try to install oggm again. Since then, it always shows the above hint.

**Comment by MatCast** [comment] 2018-11-05 15:56
> > In Spyder in order to use a different environment from the default one you have to go to:
> > Tools->Preferences->Python Interpreter: Choose "Use the following Python interpreter" and choose the path to the python installation of the oggm environment. Usually this is in the anaconda3 folder: path/to/anaconda3/envs/oggm_env/bin/python3.6.
> > ![spyder_preferences](https://user-images.githubusercontent.com/32680270/47993580-1aba7400-e0f0-11e8-943a-88aabda24826.png)
> > After this you need to restart the kernel of the ipython console. You should now be able to import oggm if it is correctly installed.
> 
> After the environment changed, could all packages I have installed except oggm be imported in Spyder?

Only packages installed in the oggm_env will be available in the kernel using this environment. You probably also need to install spyder in the oggm_env in order for it to work while using this environment.

**Comment by liyaojun** [comment] 2018-11-05 16:02
> 
> Only packages installed in the oggm_env will be available in the kernel using this environment. You probably also need to install spyder in the oggm_env in order for it to work while using this environment.


Thank you very much! Did you also install OGGM in Anaconda environment? I have failed to install too many times.

**Comment by MatCast** [comment] 2018-11-05 16:31
> Thank you very much! Did you also install OGGM in Anaconda environment? I have failed to install too many times.

I don't think the installation problem you have has anything to do with installing oggm in an environment or not. As far as i am aware, the problem is windows related unfortunately. I had oggm installed in an anaconda environment on windows but i had a lot of packages conflicts issues especially with fiona. I then installed it on Linux and it works wonders there.

**Comment by liyaojun** [comment] 2018-11-06 16:50
So sorry but I still failed to install OGGM in Ubuntu. @TimoRoth  @MatCast 
I run 'conda install -c oggm -c conda-forge oggm' and 'git clone.....' as well as 'pip install -e .' successfully. But still failed in pytest. Says'ImportError: libncurses.so.6: cannot open shared object file: No such file or directory'
OMG, please help me! 


(oggm_env) liyaojun@liyaojun-All-Series:~$ git clone https://github.com/OGGM/oggm.git
Cloning into 'oggm'...
remote: Enumerating objects: 106, done.
remote: Counting objects: 100% (106/106), done.
remote: Compressing objects: 100% (79/79), done.
remote: Total 5384 (delta 45), reused 59 (delta 27), pack-reused 5278
Receiving objects: 100% (5384/5384), 23.80 MiB | 1.98 MiB/s, done.
Resolving deltas: 100% (3823/3823), done.
(oggm_env) liyaojun@liyaojun-All-Series:~$ cd oggm
(oggm_env) liyaojun@liyaojun-All-Series:~/oggm$ pip install -e .
Obtaining file:///home/liyaojun/oggm
Requirement already satisfied: numpy in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from oggm==1.0.2+86.gdf857ff) (1.15.4)
Requirement already satisfied: scipy in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from oggm==1.0.2+86.gdf857ff) (1.1.0)
Requirement already satisfied: pyproj in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from oggm==1.0.2+86.gdf857ff) (1.9.5.1)
Requirement already satisfied: pandas in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from oggm==1.0.2+86.gdf857ff) (0.23.4)
Requirement already satisfied: GDAL in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from oggm==1.0.2+86.gdf857ff) (2.2.4)
Requirement already satisfied: geopandas in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from oggm==1.0.2+86.gdf857ff) (0.4.0)
Requirement already satisfied: fiona in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from oggm==1.0.2+86.gdf857ff) (1.7.13)
Requirement already satisfied: matplotlib>=2.0.0 in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from oggm==1.0.2+86.gdf857ff) (2.1.2)
Requirement already satisfied: scikit-image in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from oggm==1.0.2+86.gdf857ff) (0.14.1)
Requirement already satisfied: Pillow in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from oggm==1.0.2+86.gdf857ff) (5.2.0)
Requirement already satisfied: joblib in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from oggm==1.0.2+86.gdf857ff) (0.12.5)
Requirement already satisfied: netCDF4 in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from oggm==1.0.2+86.gdf857ff) (1.4.2)
Requirement already satisfied: shapely in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from oggm==1.0.2+86.gdf857ff) (1.6.4.post1)
Requirement already satisfied: rasterio in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from oggm==1.0.2+86.gdf857ff) (0.36.0)
Requirement already satisfied: configobj in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from oggm==1.0.2+86.gdf857ff) (5.0.6)
Requirement already satisfied: pytest in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from oggm==1.0.2+86.gdf857ff) (3.10.0)
Requirement already satisfied: xarray in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from oggm==1.0.2+86.gdf857ff) (0.10.9)
Requirement already satisfied: progressbar2 in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from oggm==1.0.2+86.gdf857ff) (3.38.0)
Requirement already satisfied: boto3 in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from oggm==1.0.2+86.gdf857ff) (1.9.37)
Requirement already satisfied: requests in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from oggm==1.0.2+86.gdf857ff) (2.20.0)
Requirement already satisfied: salem in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from oggm==1.0.2+86.gdf857ff) (0.2.2.dev-550bf15)
Requirement already satisfied: pytz>=2011k in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from pandas->oggm==1.0.2+86.gdf857ff) (2018.7)
Requirement already satisfied: python-dateutil>=2.5.0 in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from pandas->oggm==1.0.2+86.gdf857ff) (2.7.5)
Requirement already satisfied: cligj>=0.4 in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from fiona->oggm==1.0.2+86.gdf857ff) (0.5.0)
Requirement already satisfied: click-plugins in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from fiona->oggm==1.0.2+86.gdf857ff) (1.0.4)
Requirement already satisfied: six>=1.7 in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from fiona->oggm==1.0.2+86.gdf857ff) (1.11.0)
Requirement already satisfied: munch in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from fiona->oggm==1.0.2+86.gdf857ff) (2.3.2)
Requirement already satisfied: cycler>=0.10 in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from matplotlib>=2.0.0->oggm==1.0.2+86.gdf857ff) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from matplotlib>=2.0.0->oggm==1.0.2+86.gdf857ff) (2.3.0)
Requirement already satisfied: cloudpickle>=0.2.1 in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from scikit-image->oggm==1.0.2+86.gdf857ff) (0.6.1)
Requirement already satisfied: PyWavelets>=0.4.0 in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from scikit-image->oggm==1.0.2+86.gdf857ff) (1.0.1)
Requirement already satisfied: networkx>=1.8 in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from scikit-image->oggm==1.0.2+86.gdf857ff) (2.2)
Requirement already satisfied: dask[array]>=0.9.0 in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from scikit-image->oggm==1.0.2+86.gdf857ff) (0.20.0)
Requirement already satisfied: cftime in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from netCDF4->oggm==1.0.2+86.gdf857ff) (1.0.2.1)
Requirement already satisfied: affine in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from rasterio->oggm==1.0.2+86.gdf857ff) (2.2.1)
Requirement already satisfied: snuggs in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from rasterio->oggm==1.0.2+86.gdf857ff) (1.4.1)
Requirement already satisfied: py>=1.5.0 in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from pytest->oggm==1.0.2+86.gdf857ff) (1.7.0)
Requirement already satisfied: setuptools in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from pytest->oggm==1.0.2+86.gdf857ff) (40.5.0)
Requirement already satisfied: attrs>=17.4.0 in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from pytest->oggm==1.0.2+86.gdf857ff) (18.2.0)
Requirement already satisfied: more-itertools>=4.0.0 in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from pytest->oggm==1.0.2+86.gdf857ff) (4.3.0)
Requirement already satisfied: atomicwrites>=1.0 in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from pytest->oggm==1.0.2+86.gdf857ff) (1.2.1)
Requirement already satisfied: pluggy>=0.7 in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from pytest->oggm==1.0.2+86.gdf857ff) (0.8.0)
Requirement already satisfied: python-utils>=2.3.0 in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from progressbar2->oggm==1.0.2+86.gdf857ff) (2.3.0)
Requirement already satisfied: botocore<1.13.0,>=1.12.37 in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from boto3->oggm==1.0.2+86.gdf857ff) (1.12.37)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from boto3->oggm==1.0.2+86.gdf857ff) (0.9.3)
Requirement already satisfied: s3transfer<0.2.0,>=0.1.10 in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from boto3->oggm==1.0.2+86.gdf857ff) (0.1.13)
Requirement already satisfied: certifi>=2017.4.17 in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from requests->oggm==1.0.2+86.gdf857ff) (2018.10.15)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from requests->oggm==1.0.2+86.gdf857ff) (3.0.4)
Requirement already satisfied: idna<2.8,>=2.5 in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from requests->oggm==1.0.2+86.gdf857ff) (2.7)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from requests->oggm==1.0.2+86.gdf857ff) (1.23)
Requirement already satisfied: click<8,>=4.0 in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from cligj>=0.4->fiona->oggm==1.0.2+86.gdf857ff) (7.0)
Requirement already satisfied: decorator>=4.3.0 in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from networkx>=1.8->scikit-image->oggm==1.0.2+86.gdf857ff) (4.3.0)
Requirement already satisfied: toolz>=0.7.3; extra == "array" in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from dask[array]>=0.9.0->scikit-image->oggm==1.0.2+86.gdf857ff) (0.9.0)
Requirement already satisfied: docutils>=0.10 in /home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages (from botocore<1.13.0,>=1.12.37->boto3->oggm==1.0.2+86.gdf857ff) (0.14)
Installing collected packages: oggm
  Found existing installation: oggm 1.0.0
    Uninstalling oggm-1.0.0:
      Successfully uninstalled oggm-1.0.0
  Running setup.py develop for oggm
Successfully installed oggm
 
(oggm_env) liyaojun@liyaojun-All-Series:~/oggm$ pytest .
Traceback (most recent call last):
  File "/home/liyaojun/anaconda3/envs/oggm_env/bin/pytest", line 11, in <module>
    sys.exit(main())
  File "/home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages/_pytest/config/__init__.py", line 57, in main
    config = _prepareconfig(args, plugins)
  File "/home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages/_pytest/config/__init__.py", line 195, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages/pluggy/hooks.py", line 284, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages/pluggy/manager.py", line 67, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages/pluggy/manager.py", line 61, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages/_pytest/helpconfig.py", line 93, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages/_pytest/config/__init__.py", line 669, in pytest_cmdline_parse
    self.parse(args)
  File "/home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages/_pytest/config/__init__.py", line 841, in parse
    self._preparse(args, addopts=addopts)
  File "/home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages/_pytest/config/__init__.py", line 793, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages/pluggy/manager.py", line 267, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2343, in load
    return self.resolve()
  File "/home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2349, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/liyaojun/oggm/oggm/__init__.py", line 30, in <module>
    from oggm.utils import (GlacierDirectory, entity_task, global_task,
  File "/home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 294, in load_module
    six.exec_(co, mod.__dict__)
  File "/home/liyaojun/oggm/oggm/utils.py", line 30, in <module>
    import geopandas as gpd
  File "/home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages/geopandas/__init__.py", line 4, in <module>
    from geopandas.io.file import read_file
  File "/home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages/geopandas/io/file.py", line 3, in <module>
    import fiona
  File "/home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages/fiona/__init__.py", line 69, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
  File "/home/liyaojun/anaconda3/envs/oggm_env/lib/python3.6/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: libncurses.so.6: cannot open shared object file: No such file or directory

**Comment by liyaojun** [comment] 2018-11-06 16:53
However, after my run of 'conda install oggm' succeed, I run pytest and it's still failed. Says'collected 0 items'. And then I run 'git clone...'and get into the development mode. And the result went as above mentioned.

**Comment by liyaojun** [comment] 2018-11-06 16:54
However, after my run of 'conda install oggm' succeed, I run pytest and it's still failed. Says'collected 0 items'. And then I run 'git clone...'and get into the development mode. And the result went as above mentioned.

**Comment by TimoRoth** [comment] 2018-11-06 16:58
The missing ncurses library is a bug in anaconda, and fixed in the latest version, you'll need to update your entire base environment and the oggm environment in order to fix it.
And the pytest issue looks like you didn't run it in the oggm directoy. If you installed oggm in that env you can do --pyargs oggm instead.

**Comment by liyaojun** [comment] 2018-11-07 11:08
> The missing ncurses library is a bug in anaconda, and fixed in the latest version, you'll need to update your entire base environment and the oggm environment in order to fix it.
> And the pytest issue looks like you didn't run it in the oggm directoy. If you installed oggm in that env you can do --pyargs oggm instead.

 So sorry to interrupt so many times. I have updated all the factors you said and reinstall OGGM. But this time the progress still is interrupted by some issues.

When I run 'conda install -c oggm -c conda-forge oggm', the terminal say'"
(oggm_env) rylanlee@rylanlee-All-Series:~$ conda install -c oggm -c conda-forge oggm
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - matplotlib-base
  - oggm -&gt; matplotlib[version='2.1|2.1.*'] -&gt; freetype=2.8
Use "conda info <package>" to see the dependencies for each package."

How should I do? I am sorry that this is my first time tu use Linux.

**Comment by TimoRoth** [comment] 2018-11-07 11:51
Try just installing oggm-deps and then install oggm manually via `pip 
install -e .` from your clone. The oggm package is the older stable 
version, and it seems like some older package it depends on got one of 
its dependencies removed.

**Closed** 2018-11-14 16:13 UTC
