### ISSUE TITLE
Some questions that appeared in "use_your_own_inventory"

### ISSUE THREAD

**Issue by zhaocaicai252** [OGGM/oggm#1252] opened 2021-05-28 10:15 UTC
Hello, Mr. Developer!  
When I followed the "use_your_own_inventory" process to use custom glacier data, the following problem occurred:
![mistake](https://user-images.githubusercontent.com/75459436/119967469-f5a7ec80-bfde-11eb-8807-e232893130d3.png)
The red boxed part conflicts with the tutorial.
I chose a in Central Asia, which is similar to the Hintereisferner Glacier in the tutorial. And I used Qgis to make a template(Attributes are already consistent with the RGI dataset), the following is a screenshot of the glacier. 
![glacier](https://user-images.githubusercontent.com/75459436/119967504-fd679100-bfde-11eb-8aae-6e031fe44705.png)
Looking forward to your answer, thank you very much!!!

**Comment by fmaussion** [comment] 2021-05-31 14:52
Thanks for the very well crafted question! Next time however please do not use screenshots of code but copy paste the text of the code and the error. (screenshot of geometries is OK).

The problem is that you are using the sample data from the alps and try to select a glacier in Region 13.

I think that the work that @Keeptg is doing for OGGM might be useful for you, a new functionality will soon be available in OGGM to help you out.

**Comment by Keeptg** [comment] 2021-06-01 03:20
The functionality [`cook_rgidf`](https://github.com/OGGM/oggm/blob/8339947442e3933d330f9f4f1a63fa0bda5f1ee8/oggm/utils/_funcs.py#L785-L861) can now be used in the newest OGGM (develop verion).  It is used to rewrite a non-RGI glacier inventory following RGI format. You can import it by `from oggm.utils import cook_rgidf`. The tutorial for this function is not merged in [OGGM/tutorials](https://github.com/OGGM/tutorials) yet. But if you want to have a look now, you can download and run 'use_your_own_inventory.ipynb` in [my fork](https://github.com/Keeptg/tutorials/blob/cook_rgidf/notebooks/use_your_own_inventory.ipynb). Please update your OGGM to the newest version if you want to use 'cook_rgidf`.

**Closed** 2021-06-30 08:40 UTC
