### ISSUE TITLE
Bug in untils.py?

### ISSUE THREAD

**Issue by anoukvlug** [OGGM/oggm#151] opened 2017-01-16 13:20 UTC
The 5th of January is started using an updated version of oggm. When I run oggm the following error occured:

```
> /vega1/avlug/Programs/miniconda3/envs/oggm_env/bin/python3.5 /vega1/avlug/Programs/oggm/oggm/Anouk/run_rgi_regionSelectionTotalTest.py
> 2017-01-10 17:16:02: oggm.cfg: Parameter file: /vega1/avlug/Programs/oggm/oggm/params.cfg
> Downloading http://www.glims.org/RGI/rgi50_files/rgi50.zip ...
> 100% of 410.4 MiB |#######################| Elapsed Time: 0:01:32 Time: 0:01:32
> OrderedDict([('working_dir', '/vega1/avlug/Programs/oggm/Workspace/A3smalltest'), ('topo_dir', '/vega1/avlug/Programs/oggm/oggm-data/topo'), ('cru_dir', '/vega1/avlug/Programs/oggm/oggm-data/cru'), ('rgi_dir', '/vega1/avlug/Programs/oggm/oggm-data/rgi'), ('dem_file', '~'), ('climate_file', '~'), ('wgms_rgi_links', '~'), ('glathida_rgi_links', '~'), ('leclercq_rgi_links', '~')])
> Delete all glacier directories? [Y/n] y
> 2017-01-10 17:19:05: oggm.core.preprocessing.gis: RGI50-03.00840: define_glacier_region
> Downloading http://viewfinderpanoramas.org/dem3/T15.zip ...
> 100% of  11.2 MiB |#######################| Elapsed Time: 0:00:01 Time: 0:00:01
> 2017-01-10 17:19:07: oggm.core.preprocessing.gis: KeyError occured during task define_glacier_region on RGI50-03.00840!
> Traceback (most recent call last):
>   File "/vega1/avlug/Programs/oggm/oggm/Anouk/run_rgi_regionSelectionTotalTest.py", line 95, in <module>
>     gdirs = workflow.init_glacier_regions(rgidf, reset=True)
>   File "/vega1/avlug/Programs/oggm/oggm/workflow.py", line 120, in init_glacier_regions
>     execute_entity_task(tasks.define_glacier_region, new_gdirs)
>   File "/vega1/avlug/Programs/oggm/oggm/workflow.py", line 94, in execute_entity_task
>     pc(gdir)
>   File "/vega1/avlug/Programs/oggm/oggm/workflow.py", line 58, in __call__
>     return self.call_func(gdir, **gdir_kwargs)
>   File "/vega1/avlug/Programs/oggm/oggm/utils.py", line 1442, in _entity_task
>     out = task_func(gdir, **kwargs)
>   File "/vega1/avlug/Programs/oggm/oggm/core/preprocessing/gis.py", line 372, in define_glacier_region
>     source=source)
>   File "/vega1/avlug/Programs/oggm/oggm/utils.py", line 1235, in get_topo_file
>     sources.append(_download_dem3_viewpano(z))
>   File "/vega1/avlug/Programs/oggm/oggm/utils.py", line 283, in _download_dem3_viewpano
>     return _download_dem3_viewpano_unlocked(zone)
>   File "/vega1/avlug/Programs/oggm/oggm/utils.py", line 370, in _download_dem3_viewpano_unlocked
>     profile.pop('affine')
>   File "/vega1/avlug/Programs/miniconda3/envs/oggm_env/lib/python3.5/_collections_abc.py", line 733, in pop
>     del self[key]
>   File "/vega1/avlug/Programs/miniconda3/envs/oggm_env/lib/python3.5/collections/__init__.py", line 988, in __delitem__
>     def __delitem__(self, key): del self.data[key]
> KeyError: 'affine'
> 
> Process finished with exit code 1
```

To "solve" the error I compared the old utils.py file I had with the new one. Then I copied some parts of the new version into the old version. So I haven't found what goes precisely wrong in the new utils.py, though I got the model to run with the adjusted old version.
In the .txt file you can see the code of the utils.py file I used: 
[utils.txt](https://github.com/OGGM/oggm/files/708380/utils2.txt)
I still need to have a better look at it, but I decided to already post this in case somebody else runs into the same error.

**Comment by fmaussion** [comment] 2017-01-16 13:34
Thanks for the report! This looks very much like we have different versions of rasterio installed.

changing line https://github.com/OGGM/oggm/blob/master/oggm/utils.py#L371 and line https://github.com/OGGM/oggm/blob/master/oggm/utils.py#L1290 to:

```python
profile.pop('affine', None)
```
should solve this specific problem. Would you be interested in submitting a [PR](http://oggm.readthedocs.io/en/latest/contributing.html) to correct this?

Then, about the changes in ``utils.py``: the major difference that you are going to see here is that we included a new DEM source for polar regions of the globe (in [this PR](https://github.com/OGGM/oggm/pull/146)). DEM3 (http://viewfinderpanoramas.org/dem3.html)  is the new default topography over ASTER. So the changes in your results might be more widespread than a simple change in the code.

To conclude: if you have previous results with ASTER DEM and would not like to change them, you shouldn't update OGGM (or set the topography source manually -- I can show you how to do that). I this doesn't matter for you, I'd recommend to use the new OGGM

**Comment by anoukvlug** [comment] 2017-01-16 16:21
Thank you for your quick reply. I have rasterio 1.0a5. Which version do you use?

I just downloaded the latest version of the utils.py file to try solution you suggested, as I saw that before the weekend some new changes have been made. Now I get a new error. I will try to solve it, but if you have any suggestions on how to solve it please let me know. 

```
/vega1/avlug/Programs/miniconda3/envs/oggm_env/bin/python3.5 /vega1/avlug/Programs/oggm/oggm/Anouk/run_rgi_regionSelectionTotalTest.py
2017-01-16 16:51:15: oggm.cfg: Parameter file: /vega1/avlug/Programs/oggm/oggm/params.cfg
OrderedDict([('working_dir', '/vega1/avlug/Programs/oggm/Workspace/A3smalltest'), ('topo_dir', '/vega1/avlug/Programs/oggm/oggm-data/topo'), ('cru_dir', '/vega1/avlug/Programs/oggm/oggm-data/cru'), ('rgi_dir', '/vega1/avlug/Programs/oggm/oggm-data/rgi'), ('dem_file', '~'), ('climate_file', '/vega1/avlug/Programs/oggm/oggm-data/climate/N.f19_g16.001.cam.085001-184912.nc'), ('wgms_rgi_links', '~'), ('glathida_rgi_links', '~'), ('leclercq_rgi_links', '~'), ('climate_dir', '/vega1/avlug/Programs/oggm/oggm-data/climate')])
Delete all glacier directories? [Y/n] y
2017-01-16 16:51:20: oggm.core.preprocessing.gis: RGI50-03.00841: define_glacier_region
2017-01-16 16:51:20: oggm.core.preprocessing.gis: TypeError occured during task define_glacier_region on RGI50-03.00841!
Traceback (most recent call last):
  File "/vega1/avlug/Programs/oggm/oggm/Anouk/run_rgi_regionSelectionTotalTest.py", line 97, in <module>
    gdirs = workflow.init_glacier_regions(rgidf, reset=True)
  File "/vega1/avlug/Programs/oggm/oggm/workflow.py", line 120, in init_glacier_regions
    execute_entity_task(tasks.define_glacier_region, new_gdirs)
  File "/vega1/avlug/Programs/oggm/oggm/workflow.py", line 94, in execute_entity_task
    pc(gdir)
  File "/vega1/avlug/Programs/oggm/oggm/workflow.py", line 58, in __call__
    return self.call_func(gdir, **gdir_kwargs)
  File "/vega1/avlug/Programs/oggm/oggm/utils.py", line 1443, in _entity_task
    out = task_func(gdir, **kwargs)
  File "/vega1/avlug/Programs/oggm/oggm/core/preprocessing/gis.py", line 354, in define_glacier_region
    dxdy=(dx, -dx), pixel_ref='corner')
TypeError: __init__() got an unexpected keyword argument 'x0y0'
Process finished with exit code 1
```

Do you mean Pull Request by PR? I never have made one, but it might be a good thing to learn.

I don't have results yet that I want to keep, so I will use the new version of oggm.

**Comment by fmaussion** [comment] 2017-01-16 16:28
To solve the new error you should update salem:

``pip install --upgrade git+https://github.com/fmaussion/salem.git``

> Do you mean Pull Request by PR? I never have made one, but it might be a good thing to learn.

Yes: in my post above I linked you to this page: http://oggm.readthedocs.io/en/latest/contributing.html

It is indeed a good thing to learn if you plan to do open-source development (for OGGM or elsewhere), as this is the standard way to do this. 

Contributions are always welcome!

**Comment by anoukvlug** [comment] 2017-01-16 17:25
Thank you for the solution, it brought me one step closer in getting to model to run again. Though now I have the same error again as at the start:

> /vega1/avlug/Programs/miniconda3/envs/oggm_env/bin/python3.5 /vega1/avlug/Programs/oggm/oggm/Anouk/run_rgi_regionSelectionTotalTest.py
> 2017-01-16 18:16:10: oggm.cfg: Parameter file: /vega1/avlug/Programs/oggm/oggm/params.cfg
> OrderedDict([('working_dir', '/vega1/avlug/Programs/oggm/Workspace/A3smalltest'), ('topo_dir', '/vega1/avlug/Programs/oggm/oggm-data/topo'), ('cru_dir', '/vega1/avlug/Programs/oggm/oggm-data/cru'), ('rgi_dir', '/vega1/avlug/Programs/oggm/oggm-data/rgi'), ('dem_file', '~'), ('climate_file', '/vega1/avlug/Programs/oggm/oggm-data/climate/N.f19_g16.001.cam.085001-184912.nc'), ('wgms_rgi_links', '~'), ('glathida_rgi_links', '~'), ('leclercq_rgi_links', '~'), ('climate_dir', '/vega1/avlug/Programs/oggm/oggm-data/climate')])
Delete all glacier directories? [Y/n] y01-16 18:16:10: oggm.cfg: Parameter file: /vega1/avlug/Programs/oggm/oggm/params.cfg
> Delete all glacier directories? [Y/n] y
> 2017-01-16 18:16:16: oggm.core.preprocessing.gis: RGI50-03.00841: define_glacier_region
> 2017-01-16 18:16:16: oggm.core.preprocessing.gis: KeyError occured during task define_glacier_region on RGI50-03.00841!
> Traceback (most recent call last):
>   File "/vega1/avlug/Programs/oggm/oggm/Anouk/run_rgi_regionSelectionTotalTest.py", line 97, in <module>
>     gdirs = workflow.init_glacier_regions(rgidf, reset=True)
>   File "/vega1/avlug/Programs/oggm/oggm/workflow.py", line 120, in init_glacier_regions
>     execute_entity_task(tasks.define_glacier_region, new_gdirs)
>   File "/vega1/avlug/Programs/oggm/oggm/workflow.py", line 94, in execute_entity_task
>     pc(gdir)
>   File "/vega1/avlug/Programs/oggm/oggm/workflow.py", line 58, in __call__
>     return self.call_func(gdir, **gdir_kwargs)
>   File "/vega1/avlug/Programs/oggm/oggm/utils.py", line 1443, in _entity_task
>     out = task_func(gdir, **kwargs)
>   File "/vega1/avlug/Programs/oggm/oggm/core/preprocessing/gis.py", line 372, in define_glacier_region
>     source=source)
>   File "/vega1/avlug/Programs/oggm/oggm/utils.py", line 1236, in get_topo_file
>     sources.append(_download_dem3_viewpano(z))
>   File "/vega1/avlug/Programs/oggm/oggm/utils.py", line 284, in _download_dem3_viewpano
>     return _download_dem3_viewpano_unlocked(zone)
>   File "/vega1/avlug/Programs/oggm/oggm/utils.py", line 371, in _download_dem3_viewpano_unlocked
>     profile.pop('affine', None)
>   File "/vega1/avlug/Programs/miniconda3/envs/oggm_env/lib/python3.5/_collections_abc.py", line 733, in pop
>     del self[key]
>   File "/vega1/avlug/Programs/miniconda3/envs/oggm_env/lib/python3.5/collections/__init__.py", line 988, in __delitem__
>     def __delitem__(self, key): del self.data[key]
> KeyError: 'affine'

> Process finished with exit code 1


Once I get oggm to work again, I will try to make a pull request.

**Comment by fmaussion** [comment] 2017-01-16 17:31
This is very strange. ``pop`` shouldn't send a ``KeyError`` when called with ``None``:

```python
In [1]: profile = {}

In [2]: profile.pop('affine')
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-2-c6feb68278c0> in <module>()
----> 1 profile.pop('affine')

KeyError: 'affine'

In [3]: profile.pop('affine', None)

```

I'll try to reproduce this.

**Comment by anoukvlug** [comment] 2017-01-17 09:38
Thank you! 

When I enter the same lines you did, in the python console of pycharm. I also get a slightly different traceback, but that is probably just because I'm using Pycharm.

```
In[2]: profile = {}
In[3]: profile.pop('affine')
Traceback (most recent call last):
  File "/vega1/avlug/Programs/miniconda3/envs/oggm_env/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-c6feb68278c0>", line 1, in <module>
    profile.pop('affine')
KeyError: 'affine'
In[4]: profile.pop('affine', None)
```

**Comment by TimoRoth** [comment] 2017-01-17 10:29
What python version are you using exactly?
3.5 from Anaconda, or some other source for it?

**Comment by anoukvlug** [comment] 2017-01-17 10:33
I'm using python 3.5 from miniconda.

**Comment by TimoRoth** [comment] 2017-01-17 10:42
This is very strange.
In oggm/utils.py" line 371, right before the profile.pop('affine') line that throws the error, put a print(type(profile)), and see what it prints. I suspect it's somehow not a normal dict.

**Comment by anoukvlug** [comment] 2017-01-17 10:47
If I put that in it prints:

> <class 'rasterio.profiles.Profile'>

**Comment by TimoRoth** [comment] 2017-01-17 10:51
Just noticed. in utils.py, the profiles.pop('affine') line(s) does not add None as second parameter. So maybe all it needs is to actually add it?

**Comment by fmaussion** [comment] 2017-01-17 11:34
Yes this was my first thought but it doesn't seem to work (looks like a bug in rasterio).

What about: 

```python
if 'affine' in profile:
    profile.pop('affine')
```
?

**Comment by BtbN** [comment] 2017-01-17 11:35
Yes, that or just catching any KeyErrors and ignoring them.

**Comment by TimoRoth** [comment] 2017-01-17 11:36
Yes, that or just catching any KeyErrors and ignoring them.

**Comment by TimoRoth** [comment] 2017-01-17 13:11
That would be nice, yes!
There is another occurrence of profile.pop('affine') in utils.py that probably could use the same kind of check.

**Comment by fmaussion** [comment] 2017-01-19 09:36
Closed via https://github.com/OGGM/oggm/issues/153

**Closed by fmaussion** 2017-01-19 09:36 UTC
