### ISSUE TITLE
Documentation edit for Fresh install - gdal missing

### ISSUE THREAD

**Issue by pmlefeuvre** [OGGM/oggm#275] opened 2017-08-08 09:13 UTC
I have installed oggm on a Mac and Linux machine and the installation missed osgeo (see below). I could install it with gdal, but wonder if it should be added to oggm-deps.
 conda install -c conda-forge gdal

Cheers,
PiM

pytest .
==================================== test session starts ====================================
platform linux -- Python 3.5.3, pytest-3.2.0, py-1.4.34, pluggy-0.4.0
rootdir: /model/oggm, inifile:
plugins: hypothesis-3.11.6
collected 0 items / 5 errors 

========================================== ERRORS ===========================================
_______________________ ERROR collecting oggm/tests/test_graphics.py ________________________
ImportError while importing test module '/model/oggm/oggm/tests/test_graphics.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
oggm/tests/__init__.py:3: in <module>
    import osgeo.gdal
E   ImportError: No module named 'osgeo'
-------------------------------------- Captured stdout --------------------------------------
Downloading salem-sample-data...
________________________ ERROR collecting oggm/tests/test_models.py _________________________
ImportError while importing test module '/model/oggm/oggm/tests/test_models.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
oggm/tests/__init__.py:3: in <module>
    import osgeo.gdal
E   ImportError: No module named 'osgeo'
________________________ ERROR collecting oggm/tests/test_prepro.py _________________________
ImportError while importing test module '/model/oggm/oggm/tests/test_prepro.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
oggm/tests/__init__.py:3: in <module>
    import osgeo.gdal
E   ImportError: No module named 'osgeo'
_________________________ ERROR collecting oggm/tests/test_utils.py _________________________
ImportError while importing test module '/model/oggm/oggm/tests/test_utils.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
oggm/tests/__init__.py:3: in <module>
    import osgeo.gdal
E   ImportError: No module named 'osgeo'
_______________________ ERROR collecting oggm/tests/test_workflow.py ________________________
ImportError while importing test module '/model/oggm/oggm/tests/test_workflow.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
oggm/tests/__init__.py:3: in <module>
    import osgeo.gdal
E   ImportError: No module named 'osgeo'
!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 5 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!
================================= 5 error in 21.76 seconds ==================================

**Comment by fmaussion** [comment] 2017-08-08 14:24
Thanks for the report! Something must have happened upstream because installing gdal used to install osgeo at the same time.

I'll let @TimoRoth comment on the substance, I don't know how the oggm channel works.

**Comment by TimoRoth** [comment] 2017-08-08 16:29
This is fixed since a while, but I can't get working builds out of 
Anaconda right now. Primarily because the tests are taking way too long 
and Travis kills them. Also, some of them are failing, but I have no 
chance to look at them.

Am 08.08.2017 um 16:24 schrieb Fabien Maussion:

**Comment by TimoRoth** [comment] 2017-09-08 09:14
gdal is a dependency of the oggm and oggm-deps package on Anaconda. There really should not be any need to write it explicitly into the documentation.

**Comment by fmaussion** [comment] 2017-09-08 11:13
OK I think I don't understand what the problem is then. I understood that @pmlefeuvre was saying that he was able to do ``import gdal`` but not ``from osgeo import gdal``. Is that correct @pmlefeuvre ? 

A quick search in the repository says we have various imports in the codebase: ``import osgeo.gdal``, ``from osgeo import gdal``, ``import gdal``.  I don't remember why we need all these but since the tests are passing on CI it seems that things are still OK for us at least

**Comment by fmaussion** [comment] 2018-01-11 16:13
Closing this - if this is still an issue feel free to re-open @pmlefeuvre

**Closed by fmaussion** 2018-01-11 16:13 UTC
Labels: docs
