### ISSUE TITLE
Can we test packages installed via pip or conda?

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#577] opened 2018-10-24 19:09 UTC
I just tried it, by navigating to the package directory (given e.g. by `oggm.__file__`) and then the tests run, but:
1. ALL tests run, including those that shouldn't run like slow tests and download tests (which is a problem)
2. This is not very practical for the lambda user.

Any ideas how to deal with tests and non dev-version package install?

**Comment by TimoRoth** [comment] 2018-10-24 19:58
The issue is the conftest.py file.
If it's not in the root of the repository, testing does not work because 
it doesn't find it when testing the checked out tree.
However, as it doesn't get installed, testing the installed version of 
oggm is impossible.

 From the looks of it, it's impossible to have both. At least I can't 
find any documentation on how to properly install that file.

**Comment by fmaussion** [comment] 2018-10-25 08:17
OK, no worries. What I'll do is add a `check_install` function which will run minimal tests, for the users to check if their config seems to work as expected.

**Comment by TimoRoth** [comment] 2018-10-25 09:14
It might be possible to move the conftest file one level down, into the oggm subdir. That would install it. There was a bug in pytest that broke proper discovery of plugins, which is supposedly fixed in >=3.7.2.

**Comment by TimoRoth** [comment] 2018-10-25 14:19
This should be fixed now, leaving it open until verified.

**Comment by TimoRoth** [comment] 2018-10-25 14:31
As a note, you test an installed oggm using "pytest --pyargs oggm". Plus any of the usual arguments you'd use.

**Closed** 2018-11-22 17:13 UTC
